/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/YWRV02zBfCd
 */
import { Button } from "@/components/ui/button";
import Link from "next/link";

export function Component() {
  return (
    <div className="bg-white min-h-screen">
      {/* Navigation Bar */}
      <nav className="flex items-center justify-between px-8 py-4 bg-white border-b shadow-sm">
        <div className="flex items-center space-x-8">
          <img alt="Henry Logo" className="h-10" src="/logo.jpeg" />
          <div className="flex space-x-6">
            <Link className="text-sm text-gray-700 hover:text-gray-900 font-medium" href="#">
              Para estudiantes
            </Link>
            <Link className="text-sm text-gray-700 hover:text-gray-900 font-medium" href="#">
              Para empresas
            </Link>
          </div>
        </div>
        <div className="flex items-center space-x-6">
          <Link className="text-sm text-gray-700 hover:text-gray-900 font-medium" href="#">
            Ingresar
          </Link>
          <Button className="bg-yellow-400 hover:bg-yellow-500 text-black font-semibold px-6 py-2 rounded-md">
            Aplicar
          </Button>
        </div>
      </nav>

      {/* Hero Section */}
      <div className="flex items-center justify-center px-8 py-16 bg-white">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center w-full max-w-7xl">
          <div className="space-y-8">
            <h1 className="text-5xl lg:text-6xl font-bold text-gray-900 leading-tight">
              Comienza o acelera tu carrera en tecnología
            </h1>
            <p className="text-xl lg:text-2xl text-gray-600 leading-relaxed">
              Estudia Desarrollo Full Stack, Data Science o Data Analytics.
            </p>
            
            {/* Features List */}
            <ul className="space-y-4">
              <li className="flex items-center space-x-3 text-gray-700">
                <CheckCircleIcon className="text-green-500 flex-shrink-0" />
                <span className="text-lg">Online, en vivo y flexible</span>
              </li>
              <li className="flex items-center space-x-3 text-gray-700">
                <CheckCircleIcon className="text-green-500 flex-shrink-0" />
                <span className="text-lg">Basado en proyectos</span>
              </li>
              <li className="flex items-center space-x-3 text-gray-700">
                <CheckCircleIcon className="text-green-500 flex-shrink-0" />
                <span className="text-lg">Basado en cohortes</span>
              </li>
              <li className="flex items-center space-x-3 text-gray-700">
                <CheckCircleIcon className="text-green-500 flex-shrink-0" />
                <span className="text-lg">Garantía de Empleo</span>
              </li>
            </ul>
            
            <Button className="bg-yellow-400 hover:bg-yellow-500 text-black font-semibold px-8 py-3 text-lg rounded-md">
              Aplicar
            </Button>
          </div>
          
          <div className="flex justify-center lg:justify-end">
            <img
              alt="Estudiantes en el bootcamp"
              className="rounded-2xl shadow-2xl"
              src="/placeholder.webp"
              style={{
                aspectRatio: "4/3",
                objectFit: "cover",
                maxWidth: "500px",
                width: "100%"
              }}
            />
          </div>
        </div>
      </div>

      {/* Footer Banner */}
      <div className="bg-gray-100 py-6 text-center">
        <div className="max-w-7xl mx-auto px-8">
          <span className="text-xl font-bold text-gray-800">Bootcamp #1 de Latam</span>
        </div>
      </div>
    </div>
  );
}

function CheckCircleIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14" />
      <polyline points="22 4 12 14.01 9 11.01" />
    </svg>
  );
}

export default Component;